package ui;

import objects.Tournament;

/**
 * JFrame for changing the settings.
 * 
 * @author Jukka
 */
public class Options extends javax.swing.JFrame {
    private Tournament tournament;

    public Options(Tournament tournament) {
        this.setResizable(false);
        this.tournament = tournament;       
        initComponents();
        this.setLocationRelativeTo(null);
        checkBackUp.setSelected(tournament.getAutoBackUp());
        checkSaveQuit.setSelected(tournament.getSaveOnQuit());
        checkSaveGame.setSelected(tournament.getSaveGame());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkBackUp = new javax.swing.JCheckBox();
        checkSaveQuit = new javax.swing.JCheckBox();
        checkSaveGame = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Options");

        checkBackUp.setText("Create backup when loaded");
        checkBackUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                checkBackUpMouseReleased(evt);
            }
        });

        checkSaveQuit.setText("Save on quit");
        checkSaveQuit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                checkSaveQuitMouseReleased(evt);
            }
        });

        checkSaveGame.setText("Autosave when changing match");
        checkSaveGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                checkSaveGameMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBackUp)
                    .addComponent(checkSaveQuit)
                    .addComponent(checkSaveGame))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkBackUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkSaveQuit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkSaveGame)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkBackUpMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkBackUpMouseReleased
        tournament.setAutoBackUp(checkBackUp.isSelected());
    }//GEN-LAST:event_checkBackUpMouseReleased

    private void checkSaveQuitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkSaveQuitMouseReleased
        tournament.setSaveOnQuit(checkSaveQuit.isSelected());
    }//GEN-LAST:event_checkSaveQuitMouseReleased

    private void checkSaveGameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkSaveGameMouseReleased
        tournament.setSaveGame(checkSaveGame.isSelected());
    }//GEN-LAST:event_checkSaveGameMouseReleased
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBackUp;
    private javax.swing.JCheckBox checkSaveGame;
    private javax.swing.JCheckBox checkSaveQuit;
    // End of variables declaration//GEN-END:variables
}
