package ui;

import objects.Player;
import java.awt.print.PrinterJob;
import java.util.ArrayList;
import static javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER;


/**
 *  JFrame for viewing the scoreboard.
 * 
 * @author Jukka
 */
public class ScoreBoard extends javax.swing.JFrame {
    
    ArrayList<Player> playerList;
    /**
     * Creates new form ScoreBoard.
     */
    public ScoreBoard(ArrayList<Player> playerList) {
        this.setResizable(false);
        this.playerList = playerList;
        initComponents();
        this.setLocationRelativeTo(null);
        scoreGraphics1.addPlayerList(playerList);
        jScrollPane1.setHorizontalScrollBarPolicy(HORIZONTAL_SCROLLBAR_NEVER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        scoreGraphics1 = new tablesAndGraphics.ScoreGraphics();
        buttonPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Scoreboard");

        javax.swing.GroupLayout scoreGraphics1Layout = new javax.swing.GroupLayout(scoreGraphics1);
        scoreGraphics1.setLayout(scoreGraphics1Layout);
        scoreGraphics1Layout.setHorizontalGroup(
            scoreGraphics1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );
        scoreGraphics1Layout.setVerticalGroup(
            scoreGraphics1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 291, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(scoreGraphics1);

        buttonPrint.setText("Print");
        buttonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonPrint)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonPrint)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
    *  This method is used to print the scoreboard.
    */
    private void buttonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrintActionPerformed
        PrinterJob printJob = PrinterJob.getPrinterJob();
        //PageFormat pf = printJob.defaultPage();
        //pf.setOrientation(PageFormat.LANDSCAPE);
        printJob.setPrintable(scoreGraphics1);
        if (printJob.printDialog())
        {
            try
            {
                printJob.print();
            } // end try
            catch (Exception ex)
            {
                ex.printStackTrace();
            } // end Exception catch
        } // end if
    }//GEN-LAST:event_buttonPrintActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonPrint;
    private javax.swing.JScrollPane jScrollPane1;
    private tablesAndGraphics.ScoreGraphics scoreGraphics1;
    // End of variables declaration//GEN-END:variables
}
